name: Build Site

on:
  push:
    branches: [generator]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: generator
    - uses: actions/setup-python@v2
    - name: Run auto build
      run: |
        chmod 755 .FDoc/Automate.sh
        .FDoc/Automate.sh
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
